- CMakeLists.txt
- cryptopp/CMakeLists.txt
- cryptopp/cryptoppConfig.cmake
- test/integration/int-find-package/CMakeLists.txt
- test/integration/int-install-default/CMakeLists.txt
- test/integration/int-install-prefix/CMakeLists.txt
- test/unit/disable-feature/CMakeLists.txt
- test/unit/include-prefix/CMakeLists.txt
- test/unit/no-install/CMakeLists.txt
- test/unit/standard-cpm/CMakeLists.txt
I lowered the minimum version a bit and removed the version checks. As we require a higher version there's no need to carry compat-code for cmake 3.1 around. Also (not a separate commit) I removed the setting of the new policy, as new it will be set by cmake-minimum_required.
I think not limiting to an old version just to support old systems is a good idea, also I don't see a point in requiring the newest version without using the features it offers is not the best idea. That's why I lowered the version to the highest version it was checked for. If any newer feature is used, this should be adjusted to the needed version.
I also thought about including this as a var from one common file to ease changing of this value for all places, otoh it's maybe not required as the tests won't be …
> Little version cleanups

- cryptopp/CMakeLists.txt
- test/example-src/main.cpp
k, I now added the Interface and the code in the test to use it. This could also be the example you need for #9 (thanks to aMule). If I see this correct, the find-package test is run after all install tests, so it picks up the one with the prefix.
@abdes Have you an idea to reorder the tests so first all without and then all with prefix are run? Or do you think one test that uses the defined prefix from the interface is enough? Imho the code doesn't care about what is defined as long as a header is found, so testing this twice could be just dropped.
> Added Interface with CRYPTOPP_INSTALL_PREFIX definition and Added test for compilation with prefix

- cryptopp/CMakeLists.txt
This adds a workaround for the issue reported in #13 by overriding the object output path for `rdrand.asm`.
The workaround is only enabled when using Visual Studio as generator as Ninja is not affected.
According to a [comment on StackOverflow](https://stackoverflow.com/questions/61406734/how-to-change-the-object-file-name-through-a-cmakelists-txt#comment108633599_61406734), overriding the object output path via command-line options is not a good approach but it appears to work fine in my tests.
An alternative way to fix this would be to copy `rdrand.asm` to a different folder with a unique basename. I guess we don't want to directly rename the file since it would introduce working dir changes when the cryptopp repository is cloned. This approach would need a few more changes, that's why …
> Workaround invalid rdrand.asm output path (#13)

- CMakeLists.txt
This changes `CRYPTOPP_SOURCES` from an option (which are intended only for [boolean values](https://cmake.org/cmake/help/latest/command/option.html)) to a path cache variable. The latter correctly translates backward-slash path separators on Windows to forward slashes. Previously, attempting to set this variable to a Windows-style path would result in errors like this:
```
CMake Error at cryptopp/CMakeLists.txt:1078 (add_library):
Syntax error in cmake code when parsing string
C:\Users\Admin\.conan\data\cryptopp\8.7.0\_\_\build\5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b\src/zlib.cpp
Invalid character escape '\U'.
```
> Change CRYPTOPP_SOURCES to a path variable

- .github/workflows/cmake-build.yml
- CMakeLists.txt
- CMakePresets.json
- cmake/ResetInitialCompilerOptions.cmake
- cryptopp/cryptoppConfig.cmake
- test/integration/CMakeLists.txt
- test/integration/int-find-package/CMakeLists.txt
Strip incompatible compiler options for `MSVC` and replace them with suitable alternatives. This is mainly about the `/Zi` option replaced with `/Z7`, only impacting debug builds, but with no impact on the functionality whatsoever.
Also update the CI build workflow to use the latest version of `ccache`.
> feat: make compiler caching work for the library build

- .github/workflows/cmake-build.yml
- cryptopp/CMakeLists.txt
See #3 for more details. To be scheduled in next release of crypto++.
Check if:
* on Linux,
* AND using GNU compilers,
* AND compiler version >= 12
Then, add `-fno-devirtualize` as a compiler flag.
Also added a new matrix config for CI to build on Ubuntu-22.04 with GCC-12 to testthis change.
> fix: workaround gcc-12 with -fno-devirtualize

- .github/workflows/cmake-build.yml
- cryptopp/CMakeLists.txt
- cryptopp/sources.cmake
Go over all compiler options settings per architecture and per compiler to symchronize the `cmake` code with the `crypto++` `GNUMakefile`.
This is a major cleanup which may produce some build failures on systems for which I do not have access (such as IBM or SUN).
Fixes #30
>  refactor: synchronize compiler options setting with crypto++

- .github/workflows/cmake-build.yml
Some actions saw deprecation due to old versions of nodejs (<12) or due to changes in their API. Updated the old actions, updated the dependencies, and replaced the use of deprecated `set-output` (see https://bit.ly/3eQID5a)
> Upgrade GitHub actions

- cryptopp/CMakeLists.txt
The test programs used in `check_compile_link_option` expect the already added definitions in previous tests to be made available. Therefore, the `CRYPTOPP_COMPILE_DEFINITIONS` should be passed to cmake's `try_compile`.
> fix: check_compile_link_option should use CRYPTOPP_COMPILE_DEFINITIONS

- cryptopp/CMakeLists.txt
When building a universal binary for macOS (i.e. ```CMAKE_OSX_ARCHITECTURES="x86_64;arm64"```), the architecture detect logic currently encounters the following error because ```${target_arch}``` is unquoted:
```
CMake Error at cryptopp-cmake/cryptopp/CMakeLists.txt:188 (if):
if given arguments:
"x86_64" "arm64" "MATCHES" "(x86_64|amd64)"
Unknown arguments specified
Call Stack (most recent call first):
cryptopp-cmake/cryptopp/CMakeLists.txt:214 (check_target_architecture)
```
This PR adds quotes so that multiple returned architectures won't cause a CMake error.
> fix: Universal macOS build failing due to unquoted architectures string

- CMakeLists.txt
- cryptopp/CMakeLists.txt
1. Forgot about Android is also linux and trigger preprocessor around `config_asm.h:377`
2. Forgot to enable ASM and it leads to next errors:
```
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_ASM_COMPILE_OBJECT
```
According to cmake docs `ANDROID` variable introduced since Cmake 3.7
Closes #45
> fix: Android build for armv7-a platform (#45)

- .github/workflows/cmake-build.yml
- cryptopp/CMakeLists.txt
As promised around 4 month ago, I shortened the libomp detection for macports also.
Test for macports was added
The workarounds for creating the targets with older cmake was dropped.
> Libomp second part

- .github/workflows/cmake-build.yml
First things first:
While trying to separate the cygwin/mingw32 fixes I got absolutely confused. I'm not sure if the tests should be really run silent, as the problem was in the configure step but only the failing build was shown.
I don't know where the mingw env comes from, but it seems that the windows tests had always been run in mingw64 env. More confusing, the flags that cause this build-error aren't needed on pure mingw64 (which seems to be used judging from the path of the found compiler) so there seems to be something really messed up in this env.
I didn't delete the test runs, just in case you want some confusion, too.
> fix: also set compiler env for the tests

- CMakeLists.txt
- cryptopp/CMakeLists.txt
- test/integration/CMakeLists.txt
- test/unit/CMakeLists.txt
If the build-type is not given it will be set to a default-vaule. Default is Debug when building a git checkout, otherwise Release. I guess this is a good compromise.
Also limit the chooseable build-types to Debug or Release
And tell the tests which flavour get's built.
> Build type

- test/unit/CMakeLists.txt
- test/unit/disable-feature/CMakeLists.txt
- test/unit/include-prefix/CMakeLists.txt
- test/unit/no-install/CMakeLists.txt
- test/unit/standard-cpm/CMakeLists.txt
the unit-tests didn't run as tests/unit/unit/ was searched for them and CMAKE_CURRENT_SOURCE_DIR/.. points to test/.
I guess this file was moved somewhen in the past.
The first commit of this one went accidentally into master, I changed the name given to project to cryptopp-cmake as the fetch-sources part also uses cryptopp and overwrites cryptopp_SOURCES and we can't reach the toplevel dir easy.
> fix: reenable unit-tests

- CMakeLists.txt
- cmake/GetCryptoppSources.cmake
- cryptopp/CMakeLists.txt
- cryptopp/config.pc.in
It was less to change than I thought, After seeing that the revision isn't used the gitrevision files have been dropped also, if we really need something from there, the git executable can be used directly to get this.
If the versionupdate script is really needed, someone has to adapt it to being able to use with the new versioning, or we drop it also, as changing some numbers isn't that hard. Also we could get this directly from git.
> chore: moved project upwards

- cryptopp/CMakeLists.txt
On top of https://github.com/abdes/cryptopp-cmake/commit/899542f1f7f0e55cfa1f41cfb3e9aa9dc157eace, this is also needed to make the OpenMP option work correctly
> Fix USE_OPENMP

- CMakeLists.txt
When the cryptopp-cmake directory was not checked out with Git, but downloaded (i.e. from Github Releases), the extracted directory will not be a git repository. Calling git in the directory will cause the message 'fatal: not a git repository' during configuration, and the following string(STRIP) operation will result in configuration failure.
This commit
- silences error output from Git to prevent users seeing the 'fatal: ...' message
- checks the result code from Git to make sure the output variable is only used when Git was successful
- uses the GIT_CEILING_DIRECTORIES environment variable to prevent Git from ascending into parent directories of cryptopp-cmake and possibly finding a (different) git repository there.
Fixes abdes/cryptopp-cmake#94
> Check if git execution was successful before working with result

- cryptopp/CMakeLists.txt
Hopefully an acceptable solution for https://github.com/abdes/cryptopp-cmake/issues/89
Detect when `cmake_path(GET ... PARENT_PATH ...)` of the CMake under use is broken (returns the same path), and falls back on `get_filename_component(... DIRECTORY)`.
> build: detect and work around broken cmake_path

- cmake/TargetArch.cmake
- cryptopp/CMakeLists.txt
- Treat MSVC ARM64EC as an ARM64 target.
- Don't try setting various '-march' options for ARM64 on MSVC, where the switch does not apply.
With the accompanying changes in https://github.com/weidai11/cryptopp/pull/1257, this enables building CryptoPP for Windows ARM64EC with cryptopp-cmake.
> Fix target detection for Windows ARM64EC

- cryptopp/CMakeLists.txt
When compiling for Windows ARM64 using the MSVC toolchain but a generator other than Visual Studio, the `${CMAKE_GENERATOR_PLATFORM} MATCHES "ARM"` check fails since `CMAKE_GENERATOR_PLATFORM = ARM` is only valid for the Visual Studio generator. As a result, the compile fails on `rdrand.asm`.
This fixes the issue by also checking the detected compile architecture with `CRYPTOPP_ARM32 OR CRYPTOPP_ARMV8`.
> build: fix compiling for ARM with MSVC but not Visual Studio generator

- cryptopp/sources.cmake
When using cryptopp 8.9.0 for ppc64le I found downstream libraries failing with:
```
error: symbol lookup error: undefined symbol: _ZN8CryptoPP15CPU_ProbePower8Ev (fatal)
```
> Add missing ppc sources

- cryptopp/CMakeLists.txt
MSVC doesn't have the arm_acle.h header but cryptopp automatically defines `CRYPTOPP_ARM_ACLE_HEADER=1` if `CRYPTOPP_ARM_ACLE_HEADER` isn't defined
> fix building MSVC ARM

- cryptopp/sources.cmake
With a static build, we should not define `DllMain` because it is a method reserved to shared libraries and may create linking conflicts when `cryptopp.lib` is used by another DLL.
> sources.cmake: no DllMain with static build
